# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r:
- oldrel
- release
- devel
os:
- linux
- osx
jobs:
  exclude:
  # macOS binary packages not available for r-devel
  - r: devel
    os: osx
cache: packages
before_install:
- Rscript "deploy.R"
install:
- Rscript -e 'if (!require("rmarkdown")) install.packages("rmarkdown", repos = "https://cran.rstudio.org")'
script:
- Rscript -e 'rmarkdown::render("deploy.R")'
